main:
  steps:
    - run_dbt_job:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
            name: ${"namespaces/" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + "/jobs/dbt-cloud-run"}
            location: "us-central1"
            # No 'body: overrides' needed, as it defaults to your Dockerfile ENTRYPOINT
        result: dbt_job_result
    - complete:
        return: ${dbt_job_result}