main:
  steps:
    - call_cloud_function:
        call: http.post
        args:
          url: https://us-central1-${_projectId}.cloudfunctions.net/fetch-and-load-crypto-data
          auth:
            type: OIDC
          body:
            # We don't need to pass any arguments to our function
            # but the body is required for the HTTP POST request.
            message: "Triggered by Cloud Workflow"
        result: function_result
    - return_result:
        return: ${function_result}
