bigquery:
  outputs:
    dev:
      dataset: ck_data_tech
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: sage-artifact-464909-c3
      threads: 1
      type: bigquery
  target: dev